### ISSUE TITLE
Why this image doesn't return correct result(s)?

### ISSUE THREAD

**Issue by fireattack** [soruly/whatanime.ga#11]
Image:

![image](https://user-images.githubusercontent.com/4130991/27982891-fac49fd0-6374-11e7-8c14-f7f2f732161e.png)

Result:

![image](https://user-images.githubusercontent.com/4130991/27982893-01940774-6375-11e7-8b3f-757e75077c22.png)

The image is directly captured from the video file so it should be pretty well matched.

Actually, it showed correct result when I searched it **at the first time**.  But later when I redo, it always shows no correct results.

**Comment by fireattack** [comment]
The video source on server of this particular move seems to have black bars, but even using that doesn't give correct result:

![image](https://user-images.githubusercontent.com/4130991/27982996-fcc7e802-6377-11e7-8c6d-0801dd79305f.png)

**Comment by soruly** [comment]
Hmm, it looks like the database has grown and it's hitting some limitation on accuracy. It'll tune some params to improve this.

BTW, if may try selecting `Search in: Movie` to filter out false results

**Comment by soruly** [comment]
You should now be able to search the original scene with the original image
![image](https://user-images.githubusercontent.com/1979746/27983266-1cea25be-63eb-11e7-87a8-1ca757518a4e.png)

For the black bar issue, I may just add another source without black bars to index

BTW, I'm also working on new search algorithms which can handle black bar issues. But I'm saving money for a new server for that new engine. Take a look at https://demo.whatanime.ga
