### ISSUE TITLE
API for search

### ISSUE THREAD

**Issue by vaibhav-y** [soruly/whatanime.ga#13]
Hey, I intend to write some code that may occasionally try to query whatanime.ga with images as a functionality for [Roboragi](https://github.com/Nihilate/Roboragi).

The intent is to have a the script respond to manual queries by users through whatanime.ga results for the source image. Is there an API that I can use to achieve this?

**Comment by soruly** [comment]
Yes, the API has been in beta for a while
https://github.com/soruly/whatanime.ga#official-api-beta

**Comment by hzx905581922** [comment]
大佬，请问一下这个要怎么设置啊，一直提示连接搜索服务器失败
