### ISSUE TITLE
Android demo preview

### ISSUE THREAD

**Issue by maddog05** [soruly/whatanime.ga#14]
Hi.
here is a preview from the android imaplementation of your API.
This project will be uploaded to GitHub when I finish some fixes and optimization in UI and tutorial

https://youtu.be/Xpk1okHl88Y

Regards

**Comment by soruly** [comment]
Good work ;)
I'll add links to your project.
Please also let me know when you release the latest version on Play Store
Thanks ❤️

**Comment by Hunterismine** [comment]
我看不懂

**Comment by Hunterismine** [comment]
どうやって使うこともわからないよ、英語、難しいすぎる！

**Comment by maddog05** [comment]
@soruly 
Hi. The app is ready on PlayStore(we need to wait some hours to the app was ready), I'll add the link coming soon.

Here is the GitHub project, but I need to check some configurations and api keys to remove, later I can upload the project.
https://github.com/maddog05/whatanime-android

**Comment by maddog05** [comment]
Ready @soruly 
https://play.google.com/store/apps/details?id=com.maddog05.whatanime

**Comment by soruly** [comment]
I've added the links to your apps, great work and thanks ;)
