### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by hzx905581922** [soruly/whatanime.ga#16]
大佬，请问一下这个要怎么设置啊，一直提示连接搜索服务器失败

**Comment by soruly** [comment]
這個代碼庫公開的代碼暫時只供參考，如何使用這個程式的文檔我還沒空補上，很抱歉。
簡單來說，你需要
1. 安裝並配置 nginx, php-fpm, nodejs, mariadb, redis, java, elasticsearch, solr, liresolr, python, ffmpeg opencv
2. 按照你的檔案目錄及系統結構修改代碼~~亂七八糟的設定~~

資料庫部份是我自行修改過的 [liresolr](https://github.com/dermotte/liresolr) 。  [gist](https://gist.github.com/soruly/6d162ac7cc807e3ceb98)  
由於架構十分複雜，有太量特殊結構寫死的[shellscript和python script](https://github.com/soruly/whatanime.ga/tree/master/scripts)，要寫好完整教學需要點時間。
目前這task在project [TODO](https://github.com/soruly/whatanime.ga/projects/1)

成為社畜之後我都很少空閒時間重構了，最近還沒空更新solr 7.0 _( :3」∠)_

**Comment by soruly** [comment]
伺服器後端的部份已經全部開源了，請查看sola的說明
https://github.com/soruly/sola
