### ISSUE TITLE
[Question] Discord Channel?

### ISSUE THREAD

**Issue by misakitchi** [soruly/whatanime.ga#17]
Hello! Very Good Project! :)
Have you a Discord Channel? :)

**Comment by soruly** [comment]
Though I have a discord account, I seldom check discord );
You'd better find me via Email / Twitter / Telegram

**Comment by misakitchi** [comment]
Discord is now a very good way to have a live and growing community!
Because everybody use discord now! :D
Maybe you should create a discord channel: i say it for you :)

**Comment by soruly** [comment]
It used to have a [gitter channel](https://gitter.im/soruly/whatanime.ga), but it has been inactive for a while. Though I've plans to have some sort of community discussion forum, but it seems it'll eventually be inactive as I'm the only one who's answering all the questions. Currently Telegram and Discord somehow split user groups in two halves. I can't handle too many messages coming from two places. My focus is on infrastructure for the moment. I'll host more community channels when I'm free ;)

**Comment by soruly** [comment]
The discord channel is now open:
https://discord.gg/K9jn6Kj
