### ISSUE TITLE
Cannot paste in "Search in (anilist ID):" text area

### ISSUE THREAD

**Issue by fireattack** [soruly/whatanime.ga#18]
Title says it all.

Chrome & Firefox.

**Comment by soruly** [comment]
It seems this is due the global blocking paste event for capturing pasted images.
This can be resolved by adding this element to non-blocking whitelist.
I'll resolve this later today.
Thx for reporting ;)
ref: https://github.com/soruly/whatanime.ga/blob/master/js/index.js#L542
