### ISSUE TITLE
I think the preview/thumbnail link doesn't work

### ISSUE THREAD

**Issue by Tymec** [soruly/whatanime.ga#25]
When I use this link:
https://whatanime.ga/thumbnail.php?anilist_id=${anilist_id}&file=${encodeURIComponent(filename)}&t=${at}&token=${tokenthumb}
or this one:
https://whatanime.ga/preview.php?anilist_id=${anilist_id}&file=${encodeURIComponent(filename)}&t=${at}&token=${tokenthumb}
I just keep getting 404 Not Found.
It also might be my fault since I am kinda new to this.

**Comment by Tymec** [comment]
This is how my code looks like written in Python and I'm not sure where the problem is:

```
from urllib.parse import quote

        thumb = (
            "https://whatanime.ga/thumbnail.php?"
            "anilist_id=${}&"
            "file=${}&"
            "t=${}&"
            "token=${}"
        ).format(
            str(source_json["docs"][0]["anilist_id"]),
            quote(source_json["docs"][0]["filename"]),
            str(source_json["docs"][0]["at"]),
            source_json["docs"][0]["tokenthumb"]
        )
```

**Comment by ImUrX** [comment]
sorry, i dont really know python but what i can tell you is that this works.

**Comment by Tymec** [comment]
Oh ok, could I get a example link on how it should look like after filling in the parameters?

**Comment by ImUrX** [comment]
ehh sure?
https://i.imgur.com/sTfvRee.png

**Comment by Tymec** [comment]
Oh i see, I figured it out. My bad.
Forgot to remove the $ in front of the params.
