### ISSUE TITLE
Ctrl+V doesn't work.

### ISSUE THREAD

**Issue by fireattack** [soruly/whatanime.ga#3]
Tested in Chrome, Firefox and IE.

**Comment by soruly** [comment]
It seems the new content security policy on server has blocked that, I'm working on a fix now.
Sorry for my bad ._.

**Comment by soruly** [comment]
It should be fixed now, would you help to verify that? Thanks ;)

**Comment by fireattack** [comment]
Yeah it's fixed. Thanks.
