### ISSUE TITLE
Search time returns a very large number

### ISSUE THREAD

**Issue by soruly** [soruly/whatanime.ga#5]
Sometimes the search result shows `xxxxxx images searched in 1476699897000 seconds`
This is because liresolr has a bug in time calculation.
It should works like time = 1476701076153 - 1476699897891, but sometimes it becomes time = 1476699897000 - 0, which makes RawDocsSearchTime wrong
ref:
https://bitbucket.org/dermotte/liresolr/src/43e2ee68eb7c0df4a62506ad214a9b16ce73cefc/src/main/java/net/semanticmetadata/lire/solr/LireRequestHandler.java?at=master&fileviewer=file-view-default#LireRequestHandler.java-390

**Comment by Anshuman-Verma** [comment]
Awesome web-app, open for contributions ?

**Comment by soruly** [comment]
Yes, contributions are welcome. But for now, it'd be a bit hard to get this project to setup on your server.

**Comment by Anshuman-Verma** [comment]
I'll try my best to run this, its for anime after all.
I was truly fascinated by the project, the effort you put in, sincerely appreciate the devotion to anime. @soruly :+1:

**Comment by soruly** [comment]
Search time is not shown now, closing this issue.
