### ISSUE TITLE
Expose an API to retrieve anime info

### ISSUE THREAD

**Issue by bitinn** [soruly/whatanime.ga#7]
Seems like the next logical step (though if it gets popular you might get some heavy traffic).

I would like to use it to automatically tag _Animeshot_ screenshots, and then I can provide a better search interface using the cached data ;-)

**Comment by soruly** [comment]
How would you like to query the anime info endpoint?
Is a prefix search on `title_japanese`, `title_english`, `title_romaji`, `title_chinese`, `synonyms`, and `synonyms_chinese` enough for you?
How would / should the API / datastore handle Simplified Chinese and Traditional Chinese?

**Comment by soruly** [comment]
Let's try?
https://whatanime.ga/test?q=boku
https://whatanime.ga/test?q=%E6%88%91%E7%9A%84
https://whatanime.ga/test?q=%E3%82%BD%E3%82%A6

**Comment by bitinn** [comment]
I am thinking along the same line, but slightly simpler (for me to utilize this API):

- Given `https://whatanime.ga/?url=image_url` returns a webpage.
- We can create an API where `https://whatanime.ga/api/meta?url=image_url` returns metadata for above webpage.
- Then we can query a portion of metadata with a selector like `https://whatanime.ga/api/meta?url=image_url&selector=title_japanese,title_chinese`.

Having anime tiles in 3 languages are more than enough for my tagging purpose.

**Comment by soruly** [comment]
If the api endpoint needs to query liresolr to return the result, that would overload the server easily. (That's why there are search quotas and reCaptcha)
And err we can't do reCaptcha via API :\ so you have to wait for up to 1 hour before quota restores.

There are also potential issues by abusing the `url` param to launch attacks.
Preferably, POST the whole image to the API endpoint seems better. 
Probably it's even better to extract image feature on client side, but I haven't figured out if it's possible.

**Comment by soruly** [comment]
@bitinn In case you want to use it right now, there's an "official hack" like the telegram bot.
Though it is not documented, this is unlikely to change. In case there's any, it'd likely be on a new domain / endpoint.
https://github.com/soruly/whatanime.ga-telegram-bot/blob/master/index.js#L56
Note that this endpoint has quota limit (10 search per IP per hour). If you want more quota I may whitelist your IP.

**Comment by bitinn** [comment]
Cheers, I will get around to it soon, thx!

(From my phone)

**Comment by soruly** [comment]
API is open beta since 16 Jan 2017
See details in docs http://soruly.github.io/whatanime.ga/
